// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Patient patient
//
// swagger:model Patient
type Patient struct {

	// email
	Email *string `json:"email"`

	// full name
	FullName *string `json:"full_name"`

	// id
	ID *string `json:"id"`

	// telephone number
	TelephoneNumber *string `json:"telephone_number"`
}

// Validate validates this patient
func (m *Patient) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this patient based on context it is used
func (m *Patient) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Patient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Patient) UnmarshalBinary(b []byte) error {
	var res Patient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
