// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifications.proto

package notificationapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailRequest struct {
	Email                *EmailMessage `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetEmail() *EmailMessage {
	if m != nil {
		return m.Email
	}
	return nil
}

type SendEmailReply struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailReply) Reset()         { *m = SendEmailReply{} }
func (m *SendEmailReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailReply) ProtoMessage()    {}
func (*SendEmailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{1}
}

func (m *SendEmailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailReply.Unmarshal(m, b)
}
func (m *SendEmailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailReply.Marshal(b, m, deterministic)
}
func (m *SendEmailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailReply.Merge(m, src)
}
func (m *SendEmailReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailReply.Size(m)
}
func (m *SendEmailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailReply proto.InternalMessageInfo

func (m *SendEmailReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type EmailMessage struct {
	RecipientEmailAddress string   `protobuf:"bytes,1,opt,name=recipientEmailAddress,proto3" json:"recipientEmailAddress,omitempty"`
	Subject               string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                  string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *EmailMessage) Reset()         { *m = EmailMessage{} }
func (m *EmailMessage) String() string { return proto.CompactTextString(m) }
func (*EmailMessage) ProtoMessage()    {}
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{2}
}

func (m *EmailMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailMessage.Unmarshal(m, b)
}
func (m *EmailMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailMessage.Marshal(b, m, deterministic)
}
func (m *EmailMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailMessage.Merge(m, src)
}
func (m *EmailMessage) XXX_Size() int {
	return xxx_messageInfo_EmailMessage.Size(m)
}
func (m *EmailMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmailMessage proto.InternalMessageInfo

func (m *EmailMessage) GetRecipientEmailAddress() string {
	if m != nil {
		return m.RecipientEmailAddress
	}
	return ""
}

func (m *EmailMessage) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailRequest)(nil), "notificationapi.SendEmailRequest")
	proto.RegisterType((*SendEmailReply)(nil), "notificationapi.SendEmailReply")
	proto.RegisterType((*EmailMessage)(nil), "notificationapi.EmailMessage")
	proto.RegisterType((*Error)(nil), "notificationapi.Error")
}

func init() { proto.RegisterFile("notifications.proto", fileDescriptor_fbc3de4cce73c76f) }

var fileDescriptor_fbc3de4cce73c76f = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4a, 0x03, 0x31,
	0x14, 0x87, 0x69, 0x75, 0x94, 0x3e, 0x8b, 0x4a, 0x44, 0x1d, 0x8a, 0x62, 0xcd, 0x42, 0x5c, 0x48,
	0x07, 0x5a, 0xdd, 0xb8, 0x10, 0x5c, 0x88, 0x2b, 0x5d, 0x8c, 0x27, 0xc8, 0xcc, 0x3c, 0x87, 0xc8,
	0x34, 0x89, 0x49, 0x8a, 0xcc, 0xd6, 0x8d, 0x07, 0xf0, 0x68, 0x5e, 0xc1, 0x83, 0xc8, 0xbc, 0x69,
	0x25, 0xb4, 0xe2, 0x2e, 0x2f, 0xbf, 0x8f, 0x8f, 0xf7, 0x07, 0xf6, 0x94, 0xf6, 0xf2, 0x59, 0xe6,
	0xc2, 0x4b, 0xad, 0xdc, 0xc8, 0x58, 0xed, 0x35, 0xdb, 0x09, 0x3f, 0x85, 0x91, 0x83, 0xa3, 0x52,
	0xeb, 0xb2, 0xc2, 0x44, 0x18, 0x99, 0x08, 0xa5, 0xb4, 0x0f, 0x71, 0x7e, 0x0f, 0xbb, 0x4f, 0xa8,
	0x8a, 0xbb, 0xa9, 0x90, 0x55, 0x8a, 0xaf, 0x33, 0x74, 0x9e, 0x4d, 0x20, 0xc2, 0xa6, 0x8e, 0x3b,
	0xc3, 0xce, 0xf9, 0xd6, 0xf8, 0x78, 0xb4, 0xa4, 0x1c, 0x11, 0xfd, 0x80, 0xce, 0x89, 0x12, 0xd3,
	0x96, 0xe5, 0x37, 0xb0, 0x1d, 0x88, 0x4c, 0x55, 0xb3, 0x0b, 0x88, 0xd0, 0x5a, 0x6d, 0xe7, 0x9a,
	0x83, 0x55, 0x4d, 0x93, 0xa6, 0x2d, 0xc4, 0x2d, 0xf4, 0x43, 0x2d, 0xbb, 0x84, 0x7d, 0x8b, 0xb9,
	0x34, 0x12, 0x95, 0xa7, 0xe0, 0xb6, 0x28, 0x2c, 0x3a, 0x47, 0xb6, 0x5e, 0xfa, 0x77, 0xc8, 0x62,
	0xd8, 0x74, 0xb3, 0xec, 0x05, 0x73, 0x1f, 0x77, 0x89, 0x5b, 0x94, 0x8c, 0xc1, 0x7a, 0xa6, 0x8b,
	0x3a, 0x5e, 0xa3, 0x6f, 0x7a, 0xf3, 0x2b, 0x88, 0xa8, 0x87, 0x26, 0xcc, 0x75, 0x81, 0xe4, 0x8e,
	0x52, 0x7a, 0x37, 0xaa, 0x69, 0xdb, 0xcb, 0x42, 0x35, 0x2f, 0xc7, 0x1f, 0x1d, 0xe8, 0x3f, 0x06,
	0xb3, 0xb0, 0x37, 0xe8, 0xfd, 0xce, 0xce, 0x4e, 0x57, 0xe6, 0x5c, 0x5e, 0xf0, 0xe0, 0xe4, 0x3f,
	0xc4, 0x54, 0x35, 0x3f, 0x7b, 0xff, 0xfa, 0xfe, 0xec, 0x0e, 0xf9, 0x21, 0x5d, 0x2d, 0x84, 0x13,
	0xda, 0xf6, 0x75, 0xbb, 0xf4, 0x6c, 0x83, 0x8e, 0x38, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x75,
	0xc0, 0x6f, 0x8a, 0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error)
}

type notificationClient struct {
	cc *grpc.ClientConn
}

func NewNotificationClient(cc *grpc.ClientConn) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailReply, error) {
	out := new(SendEmailReply)
	err := c.cc.Invoke(ctx, "/notificationapi.Notification/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
type NotificationServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailReply, error)
}

// UnimplementedNotificationServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (*UnimplementedNotificationServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendEmailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notificationapi.Notification/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notificationapi.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Notification_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications.proto",
}
