// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifications.proto

package notificationapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeliveryStatus int32

const (
	DeliveryStatus_UNKNOWN   DeliveryStatus = 0
	DeliveryStatus_DELIVERED DeliveryStatus = 1
	DeliveryStatus_PENDING   DeliveryStatus = 2
	DeliveryStatus_FAILED    DeliveryStatus = 3
)

var DeliveryStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "DELIVERED",
	2: "PENDING",
	3: "FAILED",
}

var DeliveryStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"DELIVERED": 1,
	"PENDING":   2,
	"FAILED":    3,
}

func (x DeliveryStatus) String() string {
	return proto.EnumName(DeliveryStatus_name, int32(x))
}

func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{0}
}

type SendEmailRequest struct {
	Email                *EmailMessage `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetEmail() *EmailMessage {
	if m != nil {
		return m.Email
	}
	return nil
}

type EmailMessage struct {
	RecipientEmailAddress string   `protobuf:"bytes,1,opt,name=recipientEmailAddress,proto3" json:"recipientEmailAddress,omitempty"`
	Subject               string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                  string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *EmailMessage) Reset()         { *m = EmailMessage{} }
func (m *EmailMessage) String() string { return proto.CompactTextString(m) }
func (*EmailMessage) ProtoMessage()    {}
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{1}
}

func (m *EmailMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailMessage.Unmarshal(m, b)
}
func (m *EmailMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailMessage.Marshal(b, m, deterministic)
}
func (m *EmailMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailMessage.Merge(m, src)
}
func (m *EmailMessage) XXX_Size() int {
	return xxx_messageInfo_EmailMessage.Size(m)
}
func (m *EmailMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmailMessage proto.InternalMessageInfo

func (m *EmailMessage) GetRecipientEmailAddress() string {
	if m != nil {
		return m.RecipientEmailAddress
	}
	return ""
}

func (m *EmailMessage) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SendSmsRequest struct {
	Sms                  *SmsMessage `protobuf:"bytes,1,opt,name=sms,proto3" json:"sms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendSmsRequest) Reset()         { *m = SendSmsRequest{} }
func (m *SendSmsRequest) String() string { return proto.CompactTextString(m) }
func (*SendSmsRequest) ProtoMessage()    {}
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{2}
}

func (m *SendSmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSmsRequest.Unmarshal(m, b)
}
func (m *SendSmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSmsRequest.Marshal(b, m, deterministic)
}
func (m *SendSmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSmsRequest.Merge(m, src)
}
func (m *SendSmsRequest) XXX_Size() int {
	return xxx_messageInfo_SendSmsRequest.Size(m)
}
func (m *SendSmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSmsRequest proto.InternalMessageInfo

func (m *SendSmsRequest) GetSms() *SmsMessage {
	if m != nil {
		return m.Sms
	}
	return nil
}

type SendReply struct {
	Status               DeliveryStatus `protobuf:"varint,1,opt,name=status,proto3,enum=notificationapi.DeliveryStatus" json:"status,omitempty"`
	Error                *Error         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SendReply) Reset()         { *m = SendReply{} }
func (m *SendReply) String() string { return proto.CompactTextString(m) }
func (*SendReply) ProtoMessage()    {}
func (*SendReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{3}
}

func (m *SendReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendReply.Unmarshal(m, b)
}
func (m *SendReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendReply.Marshal(b, m, deterministic)
}
func (m *SendReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendReply.Merge(m, src)
}
func (m *SendReply) XXX_Size() int {
	return xxx_messageInfo_SendReply.Size(m)
}
func (m *SendReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendReply proto.InternalMessageInfo

func (m *SendReply) GetStatus() DeliveryStatus {
	if m != nil {
		return m.Status
	}
	return DeliveryStatus_UNKNOWN
}

func (m *SendReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SmsMessage struct {
	RecipientPhoneNumber string   `protobuf:"bytes,1,opt,name=recipientPhoneNumber,proto3" json:"recipientPhoneNumber,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsMessage) Reset()         { *m = SmsMessage{} }
func (m *SmsMessage) String() string { return proto.CompactTextString(m) }
func (*SmsMessage) ProtoMessage()    {}
func (*SmsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{4}
}

func (m *SmsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsMessage.Unmarshal(m, b)
}
func (m *SmsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsMessage.Marshal(b, m, deterministic)
}
func (m *SmsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsMessage.Merge(m, src)
}
func (m *SmsMessage) XXX_Size() int {
	return xxx_messageInfo_SmsMessage.Size(m)
}
func (m *SmsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SmsMessage proto.InternalMessageInfo

func (m *SmsMessage) GetRecipientPhoneNumber() string {
	if m != nil {
		return m.RecipientPhoneNumber
	}
	return ""
}

func (m *SmsMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbc3de4cce73c76f, []int{5}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterEnum("notificationapi.DeliveryStatus", DeliveryStatus_name, DeliveryStatus_value)
	proto.RegisterType((*SendEmailRequest)(nil), "notificationapi.SendEmailRequest")
	proto.RegisterType((*EmailMessage)(nil), "notificationapi.EmailMessage")
	proto.RegisterType((*SendSmsRequest)(nil), "notificationapi.SendSmsRequest")
	proto.RegisterType((*SendReply)(nil), "notificationapi.SendReply")
	proto.RegisterType((*SmsMessage)(nil), "notificationapi.SmsMessage")
	proto.RegisterType((*Error)(nil), "notificationapi.Error")
}

func init() { proto.RegisterFile("notifications.proto", fileDescriptor_fbc3de4cce73c76f) }

var fileDescriptor_fbc3de4cce73c76f = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x09, 0x49, 0x94, 0x49, 0x09, 0xd6, 0x42, 0x21, 0x0a, 0x45, 0x2d, 0x3e, 0x20, 0x84,
	0x20, 0x91, 0x5c, 0x24, 0xa4, 0x5e, 0x50, 0x25, 0x9b, 0x2a, 0xa2, 0xb8, 0x95, 0xc3, 0xc7, 0xd9,
	0x89, 0x87, 0xb0, 0x95, 0xed, 0x35, 0xbb, 0x1b, 0xa4, 0x5c, 0xf9, 0x0b, 0xfc, 0x34, 0xfe, 0x02,
	0x67, 0x7e, 0x03, 0xda, 0xb1, 0x4d, 0x4d, 0x6c, 0xf5, 0xb6, 0xb3, 0xef, 0xed, 0xcc, 0xf3, 0x9b,
	0x67, 0xb8, 0x97, 0x0a, 0xcd, 0xbf, 0xf0, 0x55, 0xa8, 0xb9, 0x48, 0xd5, 0x34, 0x93, 0x42, 0x0b,
	0x76, 0xb7, 0x7a, 0x19, 0x66, 0x7c, 0x72, 0xb0, 0x16, 0x62, 0x1d, 0xe3, 0x2c, 0xcc, 0xf8, 0x2c,
	0x4c, 0x53, 0xa1, 0xab, 0x74, 0xfb, 0x0c, 0xac, 0x05, 0xa6, 0x91, 0x97, 0x84, 0x3c, 0x0e, 0xf0,
	0xdb, 0x06, 0x95, 0x66, 0xc7, 0xd0, 0x45, 0x53, 0x8f, 0x5b, 0x47, 0xad, 0x67, 0x43, 0xe7, 0xf1,
	0x74, 0xa7, 0xe5, 0x94, 0xd8, 0xef, 0x51, 0xa9, 0x70, 0x8d, 0x41, 0xce, 0xb5, 0x25, 0xec, 0x55,
	0xaf, 0xd9, 0x2b, 0xd8, 0x97, 0xb8, 0xe2, 0x19, 0xc7, 0x54, 0x13, 0x70, 0x1a, 0x45, 0x12, 0x95,
	0xa2, 0xa6, 0x83, 0xa0, 0x19, 0x64, 0x63, 0xe8, 0xab, 0xcd, 0xf2, 0x0a, 0x57, 0x7a, 0xdc, 0x26,
	0x5e, 0x59, 0x32, 0x06, 0xb7, 0x97, 0x22, 0xda, 0x8e, 0x3b, 0x74, 0x4d, 0x67, 0xfb, 0x0d, 0x8c,
	0x8c, 0xf8, 0x45, 0xa2, 0x4a, 0xe9, 0x2f, 0xa1, 0xa3, 0x12, 0x55, 0x08, 0x7f, 0x54, 0x13, 0xbe,
	0x48, 0x54, 0x29, 0xdb, 0xf0, 0x6c, 0x09, 0x03, 0xd3, 0x20, 0xc0, 0x2c, 0xde, 0xb2, 0xd7, 0xd0,
	0x53, 0x3a, 0xd4, 0x9b, 0xfc, 0xf9, 0xc8, 0x39, 0xac, 0x3d, 0x77, 0x31, 0xe6, 0xdf, 0x51, 0x6e,
	0x17, 0x44, 0x0b, 0x0a, 0x3a, 0x7b, 0x01, 0x5d, 0x94, 0x52, 0x48, 0x92, 0x3c, 0x74, 0x1e, 0xd4,
	0xfd, 0x32, 0x68, 0x90, 0x93, 0xec, 0x0f, 0x00, 0xd7, 0x32, 0x98, 0x03, 0xf7, 0xff, 0x39, 0x71,
	0xf9, 0x55, 0xa4, 0xe8, 0x6f, 0x92, 0x25, 0xca, 0xc2, 0xa5, 0x46, 0xac, 0xd1, 0x8a, 0x0b, 0xe8,
	0xd2, 0x14, 0x03, 0xae, 0x44, 0x84, 0xd4, 0xa0, 0x1b, 0xd0, 0xd9, 0xb8, 0x9a, 0xe4, 0xf3, 0x4a,
	0x57, 0x8b, 0xd2, 0x20, 0x11, 0xea, 0x90, 0xc7, 0xaa, 0xe8, 0x56, 0x96, 0xcf, 0x3d, 0x18, 0xfd,
	0xff, 0xb9, 0x6c, 0x08, 0xfd, 0x8f, 0xfe, 0x3b, 0xff, 0xe2, 0xb3, 0x6f, 0xdd, 0x62, 0x77, 0x60,
	0xe0, 0x7a, 0xe7, 0xf3, 0x4f, 0x5e, 0xe0, 0xb9, 0x56, 0xcb, 0x60, 0x97, 0x9e, 0xef, 0xce, 0xfd,
	0x33, 0xab, 0xcd, 0x00, 0x7a, 0x6f, 0x4f, 0xe7, 0xe7, 0x9e, 0x6b, 0x75, 0x9c, 0x3f, 0x2d, 0xd8,
	0xf3, 0x2b, 0x76, 0xb0, 0xc2, 0x72, 0xda, 0x3a, 0x7b, 0x52, 0xdf, 0xd0, 0x4e, 0x18, 0x27, 0x93,
	0x46, 0x0a, 0x6d, 0xcc, 0x7e, 0xfa, 0xe3, 0xd7, 0xef, 0x9f, 0xed, 0x23, 0xfb, 0x21, 0x85, 0xbb,
	0xca, 0x9b, 0x51, 0x28, 0x4f, 0xf2, 0x6c, 0xb2, 0x2b, 0xe8, 0x17, 0x39, 0x61, 0x87, 0x8d, 0xed,
	0xae, 0x13, 0x74, 0xe3, 0x3c, 0x9b, 0xe6, 0x1d, 0xd8, 0xfb, 0xf5, 0x79, 0x2a, 0x51, 0x27, 0x26,
	0x52, 0xcb, 0x1e, 0xfd, 0x57, 0xc7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xad, 0xff, 0xa0, 0x22,
	0x9d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendReply, error)
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendReply, error)
}

type notificationClient struct {
	cc *grpc.ClientConn
}

func NewNotificationClient(cc *grpc.ClientConn) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/notificationapi.Notification/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendReply, error) {
	out := new(SendReply)
	err := c.cc.Invoke(ctx, "/notificationapi.Notification/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
type NotificationServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendReply, error)
	SendSms(context.Context, *SendSmsRequest) (*SendReply, error)
}

// UnimplementedNotificationServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (*UnimplementedNotificationServer) SendEmail(ctx context.Context, req *SendEmailRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedNotificationServer) SendSms(ctx context.Context, req *SendSmsRequest) (*SendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notificationapi.Notification/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notificationapi.Notification/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendSms(ctx, req.(*SendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notificationapi.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _Notification_SendEmail_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _Notification_SendSms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifications.proto",
}
