// Code generated by go-swagger; DO NOT EDIT.

// Package restapi PatientService
//
//  Schemes:
//    http
//  Host: 127.0.0.1
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
