// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appointments.proto

package appointmentapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppointmentStatus int32

const (
	AppointmentStatus_UNKNOWN   AppointmentStatus = 0
	AppointmentStatus_REQUESTED AppointmentStatus = 1
	AppointmentStatus_CONFIRMED AppointmentStatus = 2
)

var AppointmentStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUESTED",
	2: "CONFIRMED",
}

var AppointmentStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"REQUESTED": 1,
	"CONFIRMED": 2,
}

func (x AppointmentStatus) String() string {
	return proto.EnumName(AppointmentStatus_name, int32(x))
}

func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{0}
}

type GetAppointmentsOnStatusRequest struct {
	Status               AppointmentStatus `protobuf:"varint,1,opt,name=status,proto3,enum=appointmentapi.AppointmentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAppointmentsOnStatusRequest) Reset()         { *m = GetAppointmentsOnStatusRequest{} }
func (m *GetAppointmentsOnStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentsOnStatusRequest) ProtoMessage()    {}
func (*GetAppointmentsOnStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{0}
}

func (m *GetAppointmentsOnStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentsOnStatusRequest.Unmarshal(m, b)
}
func (m *GetAppointmentsOnStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentsOnStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetAppointmentsOnStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentsOnStatusRequest.Merge(m, src)
}
func (m *GetAppointmentsOnStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentsOnStatusRequest.Size(m)
}
func (m *GetAppointmentsOnStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentsOnStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentsOnStatusRequest proto.InternalMessageInfo

func (m *GetAppointmentsOnStatusRequest) GetStatus() AppointmentStatus {
	if m != nil {
		return m.Status
	}
	return AppointmentStatus_UNKNOWN
}

type GetAppointmentsOnStatusReply struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Appointments         []*Appointment `protobuf:"bytes,2,rep,name=appointments,proto3" json:"appointments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAppointmentsOnStatusReply) Reset()         { *m = GetAppointmentsOnStatusReply{} }
func (m *GetAppointmentsOnStatusReply) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentsOnStatusReply) ProtoMessage()    {}
func (*GetAppointmentsOnStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{1}
}

func (m *GetAppointmentsOnStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentsOnStatusReply.Unmarshal(m, b)
}
func (m *GetAppointmentsOnStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentsOnStatusReply.Marshal(b, m, deterministic)
}
func (m *GetAppointmentsOnStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentsOnStatusReply.Merge(m, src)
}
func (m *GetAppointmentsOnStatusReply) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentsOnStatusReply.Size(m)
}
func (m *GetAppointmentsOnStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentsOnStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentsOnStatusReply proto.InternalMessageInfo

func (m *GetAppointmentsOnStatusReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetAppointmentsOnStatusReply) GetAppointments() []*Appointment {
	if m != nil {
		return m.Appointments
	}
	return nil
}

type ModifyAppointmentStatusRequest struct {
	AppointmentUid       string            `protobuf:"bytes,1,opt,name=appointmentUid,proto3" json:"appointmentUid,omitempty"`
	Status               AppointmentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=appointmentapi.AppointmentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ModifyAppointmentStatusRequest) Reset()         { *m = ModifyAppointmentStatusRequest{} }
func (m *ModifyAppointmentStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyAppointmentStatusRequest) ProtoMessage()    {}
func (*ModifyAppointmentStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{2}
}

func (m *ModifyAppointmentStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyAppointmentStatusRequest.Unmarshal(m, b)
}
func (m *ModifyAppointmentStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyAppointmentStatusRequest.Marshal(b, m, deterministic)
}
func (m *ModifyAppointmentStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyAppointmentStatusRequest.Merge(m, src)
}
func (m *ModifyAppointmentStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyAppointmentStatusRequest.Size(m)
}
func (m *ModifyAppointmentStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyAppointmentStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyAppointmentStatusRequest proto.InternalMessageInfo

func (m *ModifyAppointmentStatusRequest) GetAppointmentUid() string {
	if m != nil {
		return m.AppointmentUid
	}
	return ""
}

func (m *ModifyAppointmentStatusRequest) GetStatus() AppointmentStatus {
	if m != nil {
		return m.Status
	}
	return AppointmentStatus_UNKNOWN
}

type ModifyAppointmentStatusReply struct {
	Error                *Error       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Appointment          *Appointment `protobuf:"bytes,2,opt,name=appointment,proto3" json:"appointment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ModifyAppointmentStatusReply) Reset()         { *m = ModifyAppointmentStatusReply{} }
func (m *ModifyAppointmentStatusReply) String() string { return proto.CompactTextString(m) }
func (*ModifyAppointmentStatusReply) ProtoMessage()    {}
func (*ModifyAppointmentStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{3}
}

func (m *ModifyAppointmentStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyAppointmentStatusReply.Unmarshal(m, b)
}
func (m *ModifyAppointmentStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyAppointmentStatusReply.Marshal(b, m, deterministic)
}
func (m *ModifyAppointmentStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyAppointmentStatusReply.Merge(m, src)
}
func (m *ModifyAppointmentStatusReply) XXX_Size() int {
	return xxx_messageInfo_ModifyAppointmentStatusReply.Size(m)
}
func (m *ModifyAppointmentStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyAppointmentStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyAppointmentStatusReply proto.InternalMessageInfo

func (m *ModifyAppointmentStatusReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ModifyAppointmentStatusReply) GetAppointment() *Appointment {
	if m != nil {
		return m.Appointment
	}
	return nil
}

type RequestAppointmentRequest struct {
	Appointment          *Appointment `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestAppointmentRequest) Reset()         { *m = RequestAppointmentRequest{} }
func (m *RequestAppointmentRequest) String() string { return proto.CompactTextString(m) }
func (*RequestAppointmentRequest) ProtoMessage()    {}
func (*RequestAppointmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{4}
}

func (m *RequestAppointmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAppointmentRequest.Unmarshal(m, b)
}
func (m *RequestAppointmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAppointmentRequest.Marshal(b, m, deterministic)
}
func (m *RequestAppointmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAppointmentRequest.Merge(m, src)
}
func (m *RequestAppointmentRequest) XXX_Size() int {
	return xxx_messageInfo_RequestAppointmentRequest.Size(m)
}
func (m *RequestAppointmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAppointmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAppointmentRequest proto.InternalMessageInfo

func (m *RequestAppointmentRequest) GetAppointment() *Appointment {
	if m != nil {
		return m.Appointment
	}
	return nil
}

type RequestAppointmentReply struct {
	Error                *Error       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Appointment          *Appointment `protobuf:"bytes,2,opt,name=appointment,proto3" json:"appointment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RequestAppointmentReply) Reset()         { *m = RequestAppointmentReply{} }
func (m *RequestAppointmentReply) String() string { return proto.CompactTextString(m) }
func (*RequestAppointmentReply) ProtoMessage()    {}
func (*RequestAppointmentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{5}
}

func (m *RequestAppointmentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAppointmentReply.Unmarshal(m, b)
}
func (m *RequestAppointmentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAppointmentReply.Marshal(b, m, deterministic)
}
func (m *RequestAppointmentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAppointmentReply.Merge(m, src)
}
func (m *RequestAppointmentReply) XXX_Size() int {
	return xxx_messageInfo_RequestAppointmentReply.Size(m)
}
func (m *RequestAppointmentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAppointmentReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAppointmentReply proto.InternalMessageInfo

func (m *RequestAppointmentReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RequestAppointmentReply) GetAppointment() *Appointment {
	if m != nil {
		return m.Appointment
	}
	return nil
}

type GetAppointmentsOnUserRequest struct {
	UserUid              string   `protobuf:"bytes,1,opt,name=userUid,proto3" json:"userUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppointmentsOnUserRequest) Reset()         { *m = GetAppointmentsOnUserRequest{} }
func (m *GetAppointmentsOnUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentsOnUserRequest) ProtoMessage()    {}
func (*GetAppointmentsOnUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{6}
}

func (m *GetAppointmentsOnUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentsOnUserRequest.Unmarshal(m, b)
}
func (m *GetAppointmentsOnUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentsOnUserRequest.Marshal(b, m, deterministic)
}
func (m *GetAppointmentsOnUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentsOnUserRequest.Merge(m, src)
}
func (m *GetAppointmentsOnUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentsOnUserRequest.Size(m)
}
func (m *GetAppointmentsOnUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentsOnUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentsOnUserRequest proto.InternalMessageInfo

func (m *GetAppointmentsOnUserRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type GetAppointmentsOnUserReply struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Appointments         []*Appointment `protobuf:"bytes,2,rep,name=appointments,proto3" json:"appointments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetAppointmentsOnUserReply) Reset()         { *m = GetAppointmentsOnUserReply{} }
func (m *GetAppointmentsOnUserReply) String() string { return proto.CompactTextString(m) }
func (*GetAppointmentsOnUserReply) ProtoMessage()    {}
func (*GetAppointmentsOnUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{7}
}

func (m *GetAppointmentsOnUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppointmentsOnUserReply.Unmarshal(m, b)
}
func (m *GetAppointmentsOnUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppointmentsOnUserReply.Marshal(b, m, deterministic)
}
func (m *GetAppointmentsOnUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppointmentsOnUserReply.Merge(m, src)
}
func (m *GetAppointmentsOnUserReply) XXX_Size() int {
	return xxx_messageInfo_GetAppointmentsOnUserReply.Size(m)
}
func (m *GetAppointmentsOnUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppointmentsOnUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppointmentsOnUserReply proto.InternalMessageInfo

func (m *GetAppointmentsOnUserReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetAppointmentsOnUserReply) GetAppointments() []*Appointment {
	if m != nil {
		return m.Appointments
	}
	return nil
}

type Appointment struct {
	AppointmentUid       string            `protobuf:"bytes,1,opt,name=appointmentUid,proto3" json:"appointmentUid,omitempty"`
	UserUid              string            `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	DateTime             string            `protobuf:"bytes,3,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	Location             string            `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Topic                string            `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Status               AppointmentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=appointmentapi.AppointmentStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Appointment) Reset()         { *m = Appointment{} }
func (m *Appointment) String() string { return proto.CompactTextString(m) }
func (*Appointment) ProtoMessage()    {}
func (*Appointment) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{8}
}

func (m *Appointment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Appointment.Unmarshal(m, b)
}
func (m *Appointment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Appointment.Marshal(b, m, deterministic)
}
func (m *Appointment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Appointment.Merge(m, src)
}
func (m *Appointment) XXX_Size() int {
	return xxx_messageInfo_Appointment.Size(m)
}
func (m *Appointment) XXX_DiscardUnknown() {
	xxx_messageInfo_Appointment.DiscardUnknown(m)
}

var xxx_messageInfo_Appointment proto.InternalMessageInfo

func (m *Appointment) GetAppointmentUid() string {
	if m != nil {
		return m.AppointmentUid
	}
	return ""
}

func (m *Appointment) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *Appointment) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *Appointment) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Appointment) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Appointment) GetStatus() AppointmentStatus {
	if m != nil {
		return m.Status
	}
	return AppointmentStatus_UNKNOWN
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5f4e3616349cb11, []int{9}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterEnum("appointmentapi.AppointmentStatus", AppointmentStatus_name, AppointmentStatus_value)
	proto.RegisterType((*GetAppointmentsOnStatusRequest)(nil), "appointmentapi.GetAppointmentsOnStatusRequest")
	proto.RegisterType((*GetAppointmentsOnStatusReply)(nil), "appointmentapi.GetAppointmentsOnStatusReply")
	proto.RegisterType((*ModifyAppointmentStatusRequest)(nil), "appointmentapi.ModifyAppointmentStatusRequest")
	proto.RegisterType((*ModifyAppointmentStatusReply)(nil), "appointmentapi.ModifyAppointmentStatusReply")
	proto.RegisterType((*RequestAppointmentRequest)(nil), "appointmentapi.RequestAppointmentRequest")
	proto.RegisterType((*RequestAppointmentReply)(nil), "appointmentapi.RequestAppointmentReply")
	proto.RegisterType((*GetAppointmentsOnUserRequest)(nil), "appointmentapi.GetAppointmentsOnUserRequest")
	proto.RegisterType((*GetAppointmentsOnUserReply)(nil), "appointmentapi.GetAppointmentsOnUserReply")
	proto.RegisterType((*Appointment)(nil), "appointmentapi.Appointment")
	proto.RegisterType((*Error)(nil), "appointmentapi.Error")
}

func init() { proto.RegisterFile("appointments.proto", fileDescriptor_c5f4e3616349cb11) }

var fileDescriptor_c5f4e3616349cb11 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x59, 0xb7, 0x49, 0xe9, 0x04, 0xaa, 0xb0, 0x50, 0xc5, 0x98, 0xa8, 0x4d, 0x2d, 0x41,
	0x43, 0x40, 0x09, 0x0a, 0x17, 0x40, 0x02, 0x84, 0xa8, 0x41, 0x15, 0x6a, 0x22, 0xdc, 0x46, 0x48,
	0x70, 0x32, 0xc9, 0x12, 0x59, 0x72, 0xbc, 0xc6, 0xde, 0x48, 0x44, 0x51, 0x2e, 0x20, 0x2e, 0x08,
	0x89, 0x03, 0x37, 0x6e, 0x1c, 0x79, 0x0f, 0xde, 0x80, 0x0b, 0x0f, 0x00, 0xef, 0x81, 0xbc, 0xde,
	0xd0, 0xb5, 0x1d, 0xa7, 0xc9, 0xa5, 0xa7, 0x76, 0x76, 0x3e, 0xf6, 0x37, 0x7f, 0xef, 0x4c, 0x00,
	0x5b, 0x9e, 0x47, 0x6d, 0x97, 0x0d, 0x88, 0xcb, 0x82, 0xba, 0xe7, 0x53, 0x46, 0xf1, 0x86, 0x74,
	0x66, 0x79, 0xb6, 0x56, 0xee, 0x53, 0xda, 0x77, 0x48, 0xc3, 0xf2, 0xec, 0x86, 0xe5, 0xba, 0x94,
	0x59, 0xcc, 0xa6, 0xae, 0x88, 0xd6, 0x5f, 0xc1, 0xd6, 0x53, 0xc2, 0x1e, 0x49, 0x65, 0xda, 0xee,
	0x21, 0xb3, 0xd8, 0x30, 0x30, 0xc9, 0xdb, 0x21, 0x09, 0x18, 0xbe, 0x0b, 0xf9, 0x80, 0x1f, 0xa8,
	0xa8, 0x82, 0xaa, 0x1b, 0xcd, 0x9d, 0x7a, 0xfc, 0x82, 0xba, 0x94, 0x2c, 0x32, 0x45, 0x82, 0xfe,
	0x19, 0x41, 0x39, 0xb3, 0xba, 0xe7, 0x8c, 0xf0, 0x0d, 0xc8, 0x11, 0xdf, 0xa7, 0x3e, 0x2f, 0x5d,
	0x68, 0x6e, 0x26, 0x4b, 0x1b, 0xa1, 0xd3, 0x8c, 0x62, 0xf0, 0x43, 0x38, 0x27, 0xb7, 0xab, 0x2a,
	0x95, 0x95, 0x6a, 0xa1, 0x79, 0x65, 0x0e, 0x8e, 0x19, 0x4b, 0xd0, 0x3f, 0x20, 0xd8, 0x3a, 0xa0,
	0x3d, 0xfb, 0xcd, 0x28, 0x8d, 0x2c, 0x9a, 0xbd, 0x06, 0xb2, 0x7c, 0x1d, 0xbb, 0xc7, 0xc9, 0xd6,
	0xcd, 0xc4, 0xa9, 0x24, 0x8a, 0xb2, 0xac, 0x28, 0x9f, 0x10, 0x94, 0x33, 0x29, 0x96, 0x16, 0xe5,
	0x3e, 0x14, 0x24, 0x37, 0xa7, 0x39, 0x41, 0x13, 0x39, 0x5e, 0x7f, 0x09, 0x97, 0x45, 0xeb, 0x72,
	0x88, 0x10, 0x23, 0x51, 0x1b, 0x2d, 0x59, 0xfb, 0x23, 0x82, 0xd2, 0xac, 0xe2, 0xa7, 0xdd, 0xe3,
	0x9d, 0x19, 0x8f, 0xb0, 0x13, 0x10, 0x7f, 0xda, 0xa6, 0x0a, 0x6b, 0xc3, 0x80, 0xf8, 0xc7, 0x1f,
	0x7b, 0x6a, 0x86, 0x9f, 0x4a, 0xcb, 0x48, 0x3d, 0xfd, 0xd7, 0xfb, 0x1b, 0x41, 0x41, 0xf2, 0x2e,
	0xfc, 0x54, 0xa5, 0xf6, 0x94, 0x58, 0x7b, 0x58, 0x83, 0xb3, 0x3d, 0x8b, 0x91, 0x23, 0x7b, 0x40,
	0xd4, 0x15, 0xee, 0xfa, 0x6f, 0x87, 0x3e, 0x87, 0x76, 0xf9, 0xaa, 0x50, 0x57, 0x23, 0xdf, 0xd4,
	0xc6, 0x97, 0x20, 0xc7, 0xa8, 0x67, 0x77, 0xd5, 0x1c, 0x77, 0x44, 0x86, 0x34, 0x12, 0xf9, 0x65,
	0x47, 0xa2, 0x0d, 0x39, 0xae, 0x15, 0xc6, 0xb0, 0xda, 0xa5, 0x3d, 0xc2, 0x3b, 0xc9, 0x99, 0xfc,
	0xff, 0x90, 0x7f, 0x40, 0x82, 0xc0, 0xea, 0x93, 0x29, 0xbf, 0x30, 0x43, 0x4f, 0x8f, 0x30, 0xcb,
	0x76, 0x02, 0x81, 0x3f, 0x35, 0x6b, 0x0f, 0xe0, 0x42, 0xea, 0x36, 0x5c, 0x80, 0xb5, 0x4e, 0xeb,
	0x59, 0xab, 0xfd, 0xa2, 0x55, 0x3c, 0x83, 0xcf, 0xc3, 0xba, 0x69, 0x3c, 0xef, 0x18, 0x87, 0x47,
	0xc6, 0x5e, 0x11, 0x85, 0xe6, 0xe3, 0x76, 0xeb, 0xc9, 0xbe, 0x79, 0x60, 0xec, 0x15, 0x95, 0xe6,
	0x5f, 0x05, 0x2e, 0x4a, 0x05, 0xf6, 0x5d, 0x46, 0x7c, 0xd7, 0x72, 0xf0, 0x77, 0x04, 0xa5, 0x8c,
	0x85, 0x86, 0xeb, 0xc9, 0x7e, 0xe7, 0xef, 0x55, 0xed, 0xe6, 0xc2, 0xf1, 0x9e, 0x33, 0xd2, 0xab,
	0xef, 0x7f, 0xfd, 0xf9, 0xaa, 0xe8, 0xb8, 0x12, 0xed, 0xf1, 0xe3, 0xb8, 0x46, 0xa4, 0x61, 0x63,
	0x1c, 0xfd, 0x9d, 0xe0, 0x1f, 0x08, 0x4a, 0x19, 0xfb, 0x25, 0xcd, 0x38, 0x7f, 0x1d, 0xa6, 0x19,
	0xe7, 0x2d, 0x2e, 0xfd, 0x16, 0x67, 0xac, 0x69, 0xd5, 0x14, 0xe3, 0x38, 0xfe, 0x26, 0x27, 0x02,
	0xba, 0xf9, 0x33, 0xae, 0xb3, 0xf1, 0x4e, 0xe8, 0xfc, 0x0d, 0xc1, 0xe6, 0xcc, 0xc1, 0xc3, 0x27,
	0xab, 0x26, 0x8d, 0xb6, 0x56, 0x5b, 0x30, 0x3a, 0xa4, 0xdf, 0xe5, 0xf4, 0x3b, 0x78, 0x3b, 0x45,
	0x1f, 0xce, 0x4b, 0x63, 0x2c, 0xa6, 0x66, 0x82, 0xbf, 0x20, 0xc0, 0xe9, 0xbd, 0x86, 0xaf, 0x27,
	0xef, 0xca, 0x5c, 0xac, 0xda, 0xee, 0x22, 0xa1, 0x21, 0xd3, 0x55, 0xce, 0xb4, 0xad, 0x17, 0x93,
	0x4c, 0xf7, 0xe4, 0x0d, 0xf7, 0x3a, 0xcf, 0x7f, 0xcb, 0x6f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xaa, 0xe8, 0x8d, 0x09, 0x0f, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppointmentInternalClient is the client API for AppointmentInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppointmentInternalClient interface {
	GetAppointmentsOnStatus(ctx context.Context, in *GetAppointmentsOnStatusRequest, opts ...grpc.CallOption) (*GetAppointmentsOnStatusReply, error)
	ModifyAppointmentStatus(ctx context.Context, in *ModifyAppointmentStatusRequest, opts ...grpc.CallOption) (*ModifyAppointmentStatusReply, error)
}

type appointmentInternalClient struct {
	cc *grpc.ClientConn
}

func NewAppointmentInternalClient(cc *grpc.ClientConn) AppointmentInternalClient {
	return &appointmentInternalClient{cc}
}

func (c *appointmentInternalClient) GetAppointmentsOnStatus(ctx context.Context, in *GetAppointmentsOnStatusRequest, opts ...grpc.CallOption) (*GetAppointmentsOnStatusReply, error) {
	out := new(GetAppointmentsOnStatusReply)
	err := c.cc.Invoke(ctx, "/appointmentapi.AppointmentInternal/GetAppointmentsOnStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appointmentInternalClient) ModifyAppointmentStatus(ctx context.Context, in *ModifyAppointmentStatusRequest, opts ...grpc.CallOption) (*ModifyAppointmentStatusReply, error) {
	out := new(ModifyAppointmentStatusReply)
	err := c.cc.Invoke(ctx, "/appointmentapi.AppointmentInternal/ModifyAppointmentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppointmentInternalServer is the server API for AppointmentInternal service.
type AppointmentInternalServer interface {
	GetAppointmentsOnStatus(context.Context, *GetAppointmentsOnStatusRequest) (*GetAppointmentsOnStatusReply, error)
	ModifyAppointmentStatus(context.Context, *ModifyAppointmentStatusRequest) (*ModifyAppointmentStatusReply, error)
}

// UnimplementedAppointmentInternalServer can be embedded to have forward compatible implementations.
type UnimplementedAppointmentInternalServer struct {
}

func (*UnimplementedAppointmentInternalServer) GetAppointmentsOnStatus(ctx context.Context, req *GetAppointmentsOnStatusRequest) (*GetAppointmentsOnStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppointmentsOnStatus not implemented")
}
func (*UnimplementedAppointmentInternalServer) ModifyAppointmentStatus(ctx context.Context, req *ModifyAppointmentStatusRequest) (*ModifyAppointmentStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyAppointmentStatus not implemented")
}

func RegisterAppointmentInternalServer(s *grpc.Server, srv AppointmentInternalServer) {
	s.RegisterService(&_AppointmentInternal_serviceDesc, srv)
}

func _AppointmentInternal_GetAppointmentsOnStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentsOnStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmentInternalServer).GetAppointmentsOnStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointmentapi.AppointmentInternal/GetAppointmentsOnStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmentInternalServer).GetAppointmentsOnStatus(ctx, req.(*GetAppointmentsOnStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppointmentInternal_ModifyAppointmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyAppointmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmentInternalServer).ModifyAppointmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointmentapi.AppointmentInternal/ModifyAppointmentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmentInternalServer).ModifyAppointmentStatus(ctx, req.(*ModifyAppointmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppointmentInternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appointmentapi.AppointmentInternal",
	HandlerType: (*AppointmentInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppointmentsOnStatus",
			Handler:    _AppointmentInternal_GetAppointmentsOnStatus_Handler,
		},
		{
			MethodName: "ModifyAppointmentStatus",
			Handler:    _AppointmentInternal_ModifyAppointmentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appointments.proto",
}

// AppointmentExternalClient is the client API for AppointmentExternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppointmentExternalClient interface {
	GetAppointmentsOnUser(ctx context.Context, in *GetAppointmentsOnUserRequest, opts ...grpc.CallOption) (*GetAppointmentsOnUserReply, error)
	RequestAppointment(ctx context.Context, in *RequestAppointmentRequest, opts ...grpc.CallOption) (*RequestAppointmentReply, error)
}

type appointmentExternalClient struct {
	cc *grpc.ClientConn
}

func NewAppointmentExternalClient(cc *grpc.ClientConn) AppointmentExternalClient {
	return &appointmentExternalClient{cc}
}

func (c *appointmentExternalClient) GetAppointmentsOnUser(ctx context.Context, in *GetAppointmentsOnUserRequest, opts ...grpc.CallOption) (*GetAppointmentsOnUserReply, error) {
	out := new(GetAppointmentsOnUserReply)
	err := c.cc.Invoke(ctx, "/appointmentapi.AppointmentExternal/GetAppointmentsOnUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appointmentExternalClient) RequestAppointment(ctx context.Context, in *RequestAppointmentRequest, opts ...grpc.CallOption) (*RequestAppointmentReply, error) {
	out := new(RequestAppointmentReply)
	err := c.cc.Invoke(ctx, "/appointmentapi.AppointmentExternal/RequestAppointment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppointmentExternalServer is the server API for AppointmentExternal service.
type AppointmentExternalServer interface {
	GetAppointmentsOnUser(context.Context, *GetAppointmentsOnUserRequest) (*GetAppointmentsOnUserReply, error)
	RequestAppointment(context.Context, *RequestAppointmentRequest) (*RequestAppointmentReply, error)
}

// UnimplementedAppointmentExternalServer can be embedded to have forward compatible implementations.
type UnimplementedAppointmentExternalServer struct {
}

func (*UnimplementedAppointmentExternalServer) GetAppointmentsOnUser(ctx context.Context, req *GetAppointmentsOnUserRequest) (*GetAppointmentsOnUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppointmentsOnUser not implemented")
}
func (*UnimplementedAppointmentExternalServer) RequestAppointment(ctx context.Context, req *RequestAppointmentRequest) (*RequestAppointmentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAppointment not implemented")
}

func RegisterAppointmentExternalServer(s *grpc.Server, srv AppointmentExternalServer) {
	s.RegisterService(&_AppointmentExternal_serviceDesc, srv)
}

func _AppointmentExternal_GetAppointmentsOnUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentsOnUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmentExternalServer).GetAppointmentsOnUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointmentapi.AppointmentExternal/GetAppointmentsOnUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmentExternalServer).GetAppointmentsOnUser(ctx, req.(*GetAppointmentsOnUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppointmentExternal_RequestAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAppointmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppointmentExternalServer).RequestAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointmentapi.AppointmentExternal/RequestAppointment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppointmentExternalServer).RequestAppointment(ctx, req.(*RequestAppointmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppointmentExternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appointmentapi.AppointmentExternal",
	HandlerType: (*AppointmentExternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppointmentsOnUser",
			Handler:    _AppointmentExternal_GetAppointmentsOnUser_Handler,
		},
		{
			MethodName: "RequestAppointment",
			Handler:    _AppointmentExternal_RequestAppointment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appointments.proto",
}
