// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flightinfo.proto

package flightinfoapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Direction int32

const (
	Direction_DIRECTION_UNKNOWN Direction = 0
	Direction_ARRIVAL           Direction = 1
	Direction_DEPARTURE         Direction = 2
)

var Direction_name = map[int32]string{
	0: "DIRECTION_UNKNOWN",
	1: "ARRIVAL",
	2: "DEPARTURE",
}

var Direction_value = map[string]int32{
	"DIRECTION_UNKNOWN": 0,
	"ARRIVAL":           1,
	"DEPARTURE":         2,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{0}
}

type FlightStatus int32

const (
	FlightStatus_FLIGHT_STATUS_UNKNOWN FlightStatus = 0
	FlightStatus_DEPARTING             FlightStatus = 1
	FlightStatus_DEPARTED              FlightStatus = 2
	FlightStatus_LANDING               FlightStatus = 3
	FlightStatus_LANDED                FlightStatus = 4
)

var FlightStatus_name = map[int32]string{
	0: "FLIGHT_STATUS_UNKNOWN",
	1: "DEPARTING",
	2: "DEPARTED",
	3: "LANDING",
	4: "LANDED",
}

var FlightStatus_value = map[string]int32{
	"FLIGHT_STATUS_UNKNOWN": 0,
	"DEPARTING":             1,
	"DEPARTED":              2,
	"LANDING":               3,
	"LANDED":                4,
}

func (x FlightStatus) String() string {
	return proto.EnumName(FlightStatus_name, int32(x))
}

func (FlightStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{1}
}

type GetInfoOnFlightRequest struct {
	Date                 *Date     `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Direction            Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=flightinfoapi.Direction" json:"direction,omitempty"`
	FlightNumber         string    `protobuf:"bytes,3,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetInfoOnFlightRequest) Reset()         { *m = GetInfoOnFlightRequest{} }
func (m *GetInfoOnFlightRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoOnFlightRequest) ProtoMessage()    {}
func (*GetInfoOnFlightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{0}
}

func (m *GetInfoOnFlightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoOnFlightRequest.Unmarshal(m, b)
}
func (m *GetInfoOnFlightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoOnFlightRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoOnFlightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoOnFlightRequest.Merge(m, src)
}
func (m *GetInfoOnFlightRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoOnFlightRequest.Size(m)
}
func (m *GetInfoOnFlightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoOnFlightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoOnFlightRequest proto.InternalMessageInfo

func (m *GetInfoOnFlightRequest) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *GetInfoOnFlightRequest) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (m *GetInfoOnFlightRequest) GetFlightNumber() string {
	if m != nil {
		return m.FlightNumber
	}
	return ""
}

type GetFlightReply struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Flight               *Flight  `protobuf:"bytes,2,opt,name=flight,proto3" json:"flight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFlightReply) Reset()         { *m = GetFlightReply{} }
func (m *GetFlightReply) String() string { return proto.CompactTextString(m) }
func (*GetFlightReply) ProtoMessage()    {}
func (*GetFlightReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{1}
}

func (m *GetFlightReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFlightReply.Unmarshal(m, b)
}
func (m *GetFlightReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFlightReply.Marshal(b, m, deterministic)
}
func (m *GetFlightReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFlightReply.Merge(m, src)
}
func (m *GetFlightReply) XXX_Size() int {
	return xxx_messageInfo_GetFlightReply.Size(m)
}
func (m *GetFlightReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFlightReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetFlightReply proto.InternalMessageInfo

func (m *GetFlightReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *GetFlightReply) GetFlight() *Flight {
	if m != nil {
		return m.Flight
	}
	return nil
}

type HistoryRequest struct {
	StartDate            *Date    `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRequest) Reset()         { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()    {}
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{2}
}

func (m *HistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRequest.Unmarshal(m, b)
}
func (m *HistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRequest.Marshal(b, m, deterministic)
}
func (m *HistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRequest.Merge(m, src)
}
func (m *HistoryRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryRequest.Size(m)
}
func (m *HistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRequest proto.InternalMessageInfo

func (m *HistoryRequest) GetStartDate() *Date {
	if m != nil {
		return m.StartDate
	}
	return nil
}

type FlightPdu struct {
	// Types that are valid to be assigned to Payload:
	//	*FlightPdu_Heartbeat
	//	*FlightPdu_Flight
	Payload              isFlightPdu_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FlightPdu) Reset()         { *m = FlightPdu{} }
func (m *FlightPdu) String() string { return proto.CompactTextString(m) }
func (*FlightPdu) ProtoMessage()    {}
func (*FlightPdu) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{3}
}

func (m *FlightPdu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlightPdu.Unmarshal(m, b)
}
func (m *FlightPdu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlightPdu.Marshal(b, m, deterministic)
}
func (m *FlightPdu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlightPdu.Merge(m, src)
}
func (m *FlightPdu) XXX_Size() int {
	return xxx_messageInfo_FlightPdu.Size(m)
}
func (m *FlightPdu) XXX_DiscardUnknown() {
	xxx_messageInfo_FlightPdu.DiscardUnknown(m)
}

var xxx_messageInfo_FlightPdu proto.InternalMessageInfo

type isFlightPdu_Payload interface {
	isFlightPdu_Payload()
}

type FlightPdu_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type FlightPdu_Flight struct {
	Flight *Flight `protobuf:"bytes,2,opt,name=flight,proto3,oneof"`
}

func (*FlightPdu_Heartbeat) isFlightPdu_Payload() {}

func (*FlightPdu_Flight) isFlightPdu_Payload() {}

func (m *FlightPdu) GetPayload() isFlightPdu_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FlightPdu) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetPayload().(*FlightPdu_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *FlightPdu) GetFlight() *Flight {
	if x, ok := m.GetPayload().(*FlightPdu_Flight); ok {
		return x.Flight
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FlightPdu) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FlightPdu_Heartbeat)(nil),
		(*FlightPdu_Flight)(nil),
	}
}

type Heartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{4}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

type Flight struct {
	FlightUid            string       `protobuf:"bytes,1,opt,name=flightUid,proto3" json:"flightUid,omitempty"`
	FlightNumber         string       `protobuf:"bytes,2,opt,name=flightNumber,proto3" json:"flightNumber,omitempty"`
	Direction            Direction    `protobuf:"varint,3,opt,name=direction,proto3,enum=flightinfoapi.Direction" json:"direction,omitempty"`
	Date                 *Date        `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	ScheduledTime        *Time        `protobuf:"bytes,5,opt,name=scheduledTime,proto3" json:"scheduledTime,omitempty"`
	Origin               string       `protobuf:"bytes,6,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string       `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	Status               FlightStatus `protobuf:"varint,8,opt,name=status,proto3,enum=flightinfoapi.FlightStatus" json:"status,omitempty"`
	ActualTime           *Time        `protobuf:"bytes,9,opt,name=actualTime,proto3" json:"actualTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Flight) Reset()         { *m = Flight{} }
func (m *Flight) String() string { return proto.CompactTextString(m) }
func (*Flight) ProtoMessage()    {}
func (*Flight) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{5}
}

func (m *Flight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flight.Unmarshal(m, b)
}
func (m *Flight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flight.Marshal(b, m, deterministic)
}
func (m *Flight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flight.Merge(m, src)
}
func (m *Flight) XXX_Size() int {
	return xxx_messageInfo_Flight.Size(m)
}
func (m *Flight) XXX_DiscardUnknown() {
	xxx_messageInfo_Flight.DiscardUnknown(m)
}

var xxx_messageInfo_Flight proto.InternalMessageInfo

func (m *Flight) GetFlightUid() string {
	if m != nil {
		return m.FlightUid
	}
	return ""
}

func (m *Flight) GetFlightNumber() string {
	if m != nil {
		return m.FlightNumber
	}
	return ""
}

func (m *Flight) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (m *Flight) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Flight) GetScheduledTime() *Time {
	if m != nil {
		return m.ScheduledTime
	}
	return nil
}

func (m *Flight) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Flight) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Flight) GetStatus() FlightStatus {
	if m != nil {
		return m.Status
	}
	return FlightStatus_FLIGHT_STATUS_UNKNOWN
}

func (m *Flight) GetActualTime() *Time {
	if m != nil {
		return m.ActualTime
	}
	return nil
}

type Acknowledgement struct {
	FlightUid            string   `protobuf:"bytes,1,opt,name=flightUid,proto3" json:"flightUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Acknowledgement) Reset()         { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()    {}
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{6}
}

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Acknowledgement.Unmarshal(m, b)
}
func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Acknowledgement.Marshal(b, m, deterministic)
}
func (m *Acknowledgement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Acknowledgement.Merge(m, src)
}
func (m *Acknowledgement) XXX_Size() int {
	return xxx_messageInfo_Acknowledgement.Size(m)
}
func (m *Acknowledgement) XXX_DiscardUnknown() {
	xxx_messageInfo_Acknowledgement.DiscardUnknown(m)
}

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetFlightUid() string {
	if m != nil {
		return m.FlightUid
	}
	return ""
}

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{7}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Time struct {
	Hour                 int32    `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute               int32    `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	Second               int32    `protobuf:"varint,3,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{8}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *Time) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *Time) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_915e3e8708f9db11, []int{9}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("flightinfoapi.Direction", Direction_name, Direction_value)
	proto.RegisterEnum("flightinfoapi.FlightStatus", FlightStatus_name, FlightStatus_value)
	proto.RegisterType((*GetInfoOnFlightRequest)(nil), "flightinfoapi.GetInfoOnFlightRequest")
	proto.RegisterType((*GetFlightReply)(nil), "flightinfoapi.GetFlightReply")
	proto.RegisterType((*HistoryRequest)(nil), "flightinfoapi.HistoryRequest")
	proto.RegisterType((*FlightPdu)(nil), "flightinfoapi.FlightPdu")
	proto.RegisterType((*Heartbeat)(nil), "flightinfoapi.Heartbeat")
	proto.RegisterType((*Flight)(nil), "flightinfoapi.Flight")
	proto.RegisterType((*Acknowledgement)(nil), "flightinfoapi.Acknowledgement")
	proto.RegisterType((*Date)(nil), "flightinfoapi.Date")
	proto.RegisterType((*Time)(nil), "flightinfoapi.Time")
	proto.RegisterType((*Error)(nil), "flightinfoapi.Error")
}

func init() { proto.RegisterFile("flightinfo.proto", fileDescriptor_915e3e8708f9db11) }

var fileDescriptor_915e3e8708f9db11 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5d, 0x4f, 0xdb, 0x4a,
	0x10, 0x8d, 0xf3, 0x89, 0x27, 0x10, 0xcc, 0x5c, 0x40, 0xbe, 0xdc, 0x0f, 0x45, 0x96, 0xae, 0x6e,
	0x84, 0x54, 0xa0, 0x41, 0xad, 0xda, 0x97, 0x4a, 0x81, 0x84, 0x24, 0x05, 0x05, 0xb4, 0x49, 0x5a,
	0xf5, 0x09, 0x2d, 0xf1, 0x92, 0x58, 0x24, 0xde, 0xd4, 0x5e, 0xab, 0x4a, 0xdf, 0xfa, 0xda, 0xff,
	0xd0, 0xbf, 0xd0, 0xdf, 0x58, 0xed, 0xda, 0xce, 0x87, 0x49, 0x05, 0x6f, 0x3b, 0x3b, 0x67, 0xcf,
	0x1c, 0xcf, 0x99, 0x4c, 0xc0, 0xb8, 0x1f, 0x3b, 0xc3, 0x91, 0x70, 0xdc, 0x7b, 0x7e, 0x34, 0xf5,
	0xb8, 0xe0, 0xb8, 0xb5, 0xb8, 0xa1, 0x53, 0xc7, 0xfa, 0xa1, 0xc1, 0x7e, 0x93, 0x89, 0xb6, 0x7b,
	0xcf, 0xaf, 0xdd, 0x0b, 0x95, 0x22, 0xec, 0x73, 0xc0, 0x7c, 0x81, 0xff, 0x43, 0xd6, 0xa6, 0x82,
	0x99, 0x5a, 0x59, 0xab, 0x14, 0xab, 0x7f, 0x1c, 0xad, 0x3c, 0x3c, 0xaa, 0x53, 0xc1, 0x88, 0x02,
	0xe0, 0x6b, 0xd0, 0x6d, 0xc7, 0x63, 0x03, 0xe1, 0x70, 0xd7, 0x4c, 0x97, 0xb5, 0x4a, 0xa9, 0x6a,
	0x26, 0xd1, 0x71, 0x9e, 0x2c, 0xa0, 0x68, 0xc1, 0x66, 0x88, 0xea, 0x04, 0x93, 0x3b, 0xe6, 0x99,
	0x99, 0xb2, 0x56, 0xd1, 0xc9, 0xca, 0x9d, 0xf5, 0x00, 0xa5, 0x26, 0x13, 0xb1, 0xb0, 0xe9, 0x78,
	0x86, 0x87, 0x90, 0x63, 0x9e, 0xc7, 0xbd, 0x48, 0xd7, 0x6e, 0xa2, 0x52, 0x43, 0xe6, 0x48, 0x08,
	0xc1, 0x17, 0x90, 0x0f, 0xb3, 0x4a, 0x56, 0xb1, 0xba, 0x97, 0x00, 0x47, 0xbc, 0x11, 0xc8, 0x3a,
	0x87, 0x52, 0xcb, 0xf1, 0x05, 0xf7, 0x66, 0x71, 0x0f, 0x5e, 0x82, 0xee, 0x0b, 0xea, 0x89, 0xfa,
	0x13, 0x8d, 0x58, 0xa0, 0xac, 0x6f, 0x1a, 0xe8, 0x21, 0xef, 0x8d, 0x1d, 0xe0, 0x1b, 0xd0, 0x47,
	0x8c, 0x7a, 0xe2, 0x8e, 0x51, 0x11, 0x11, 0x24, 0x7b, 0xd3, 0x8a, 0xf3, 0xad, 0x14, 0x59, 0x80,
	0xf1, 0xf8, 0x59, 0xda, 0x5b, 0xa9, 0x58, 0xfd, 0x99, 0x0e, 0x85, 0x29, 0x9d, 0x8d, 0x39, 0xb5,
	0xad, 0x22, 0xe8, 0x73, 0x56, 0xeb, 0x7b, 0x06, 0xf2, 0x21, 0x18, 0xff, 0x06, 0x3d, 0x04, 0xf7,
	0x1d, 0x5b, 0xa9, 0xd1, 0xc9, 0xe2, 0xe2, 0x91, 0x1f, 0xe9, 0xc7, 0x7e, 0xac, 0x7a, 0x9d, 0x79,
	0xbe, 0xd7, 0xf1, 0x30, 0x65, 0x9f, 0x1a, 0xa6, 0xb7, 0xb0, 0xe5, 0x0f, 0x46, 0xcc, 0x0e, 0xc6,
	0xcc, 0xee, 0x39, 0x13, 0x66, 0xe6, 0xd6, 0xbe, 0x90, 0x29, 0xb2, 0x8a, 0xc4, 0x7d, 0xc8, 0x73,
	0xcf, 0x19, 0x3a, 0xae, 0x99, 0x57, 0xca, 0xa3, 0x08, 0xcb, 0x50, 0xb4, 0x99, 0x2f, 0x1c, 0x97,
	0x2a, 0xd5, 0x05, 0x95, 0x5c, 0xbe, 0xc2, 0x53, 0xc8, 0xfb, 0x82, 0x8a, 0xc0, 0x37, 0x37, 0xd4,
	0x27, 0xfd, 0xb5, 0xb6, 0xd7, 0x5d, 0x05, 0x21, 0x11, 0x14, 0x4f, 0x01, 0xe8, 0x40, 0x04, 0x74,
	0xac, 0x64, 0xea, 0xbf, 0x97, 0xb9, 0x04, 0xb3, 0x8e, 0x61, 0xbb, 0x36, 0x78, 0x70, 0xf9, 0x97,
	0x31, 0xb3, 0x87, 0x6c, 0xc2, 0xdc, 0x27, 0x4c, 0xb1, 0xce, 0x20, 0x2b, 0xbb, 0x83, 0x08, 0xd9,
	0x19, 0xa3, 0xe1, 0xd4, 0xe7, 0x88, 0x3a, 0xe3, 0x2e, 0xe4, 0x26, 0xdc, 0x15, 0x23, 0xe5, 0x54,
	0x8e, 0x84, 0x01, 0x1a, 0x90, 0xb1, 0xe9, 0x4c, 0x99, 0x93, 0x23, 0xf2, 0x68, 0xbd, 0x87, 0xac,
	0x6a, 0x10, 0x42, 0x76, 0xc4, 0x83, 0x39, 0x87, 0x3c, 0xcb, 0xa6, 0x4d, 0x1c, 0x37, 0x10, 0x2c,
	0x22, 0x89, 0x22, 0x79, 0xef, 0xb3, 0x01, 0x77, 0xed, 0x88, 0x28, 0x8a, 0xac, 0x57, 0x90, 0x53,
	0x3f, 0x31, 0x49, 0x36, 0xe0, 0x36, 0x8b, 0xc9, 0xe4, 0x19, 0x4d, 0x28, 0x4c, 0x98, 0xef, 0xd3,
	0x21, 0x8b, 0x86, 0x27, 0x0e, 0x0f, 0xdf, 0x81, 0x3e, 0x9f, 0x0b, 0xdc, 0x83, 0x9d, 0x7a, 0x9b,
	0x34, 0xce, 0x7b, 0xed, 0xeb, 0xce, 0x6d, 0xbf, 0x73, 0xd9, 0xb9, 0xfe, 0xd8, 0x31, 0x52, 0x58,
	0x84, 0x42, 0x8d, 0x90, 0xf6, 0x87, 0xda, 0x95, 0xa1, 0xe1, 0x16, 0xe8, 0xf5, 0xc6, 0x4d, 0x8d,
	0xf4, 0xfa, 0xa4, 0x61, 0xa4, 0x0f, 0x6f, 0x61, 0x73, 0xd9, 0x04, 0xfc, 0x13, 0xf6, 0x2e, 0xae,
	0xda, 0xcd, 0x56, 0xef, 0xb6, 0xdb, 0xab, 0xf5, 0xfa, 0xdd, 0x25, 0x9a, 0xf9, 0xcb, 0x76, 0xa7,
	0x69, 0x68, 0xb8, 0x09, 0x1b, 0x61, 0xd8, 0xa8, 0x1b, 0x69, 0x59, 0xe3, 0xaa, 0xd6, 0xa9, 0xcb,
	0x54, 0x06, 0x01, 0xf2, 0x32, 0x68, 0xd4, 0x8d, 0x6c, 0xf5, 0x01, 0x4a, 0x61, 0x01, 0xb9, 0x0a,
	0xbb, 0x33, 0x77, 0x80, 0x9f, 0x60, 0x3b, 0xb1, 0x19, 0xf1, 0xbf, 0x84, 0xbd, 0xeb, 0x37, 0xe7,
	0xc1, 0x3f, 0x8f, 0x61, 0x4b, 0x1b, 0xcc, 0x4a, 0x55, 0x7f, 0x6a, 0xb0, 0xbd, 0xa8, 0x56, 0xf3,
	0x65, 0xb9, 0x0b, 0x80, 0x26, 0x13, 0xd1, 0xfe, 0xc1, 0x24, 0xc5, 0xea, 0x5e, 0x3a, 0x58, 0xbf,
	0x0c, 0xac, 0xd4, 0x89, 0x86, 0x5d, 0xd8, 0xb9, 0x64, 0x6c, 0x2a, 0x3f, 0x61, 0xe4, 0x71, 0xd7,
	0xf9, 0xea, 0xb8, 0x43, 0xfc, 0x37, 0x81, 0x4f, 0xcc, 0xe0, 0x81, 0xb9, 0x96, 0xef, 0xc6, 0x0e,
	0xac, 0x54, 0x45, 0x3b, 0xd1, 0xee, 0xf2, 0xea, 0xcf, 0xe3, 0xf4, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x60, 0x70, 0x9a, 0xee, 0x50, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlightInfoSyncClient is the client API for FlightInfoSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlightInfoSyncClient interface {
	GetInfoOnFlight(ctx context.Context, in *GetInfoOnFlightRequest, opts ...grpc.CallOption) (*GetFlightReply, error)
}

type flightInfoSyncClient struct {
	cc *grpc.ClientConn
}

func NewFlightInfoSyncClient(cc *grpc.ClientConn) FlightInfoSyncClient {
	return &flightInfoSyncClient{cc}
}

func (c *flightInfoSyncClient) GetInfoOnFlight(ctx context.Context, in *GetInfoOnFlightRequest, opts ...grpc.CallOption) (*GetFlightReply, error) {
	out := new(GetFlightReply)
	err := c.cc.Invoke(ctx, "/flightinfoapi.FlightInfoSync/GetInfoOnFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlightInfoSyncServer is the server API for FlightInfoSync service.
type FlightInfoSyncServer interface {
	GetInfoOnFlight(context.Context, *GetInfoOnFlightRequest) (*GetFlightReply, error)
}

// UnimplementedFlightInfoSyncServer can be embedded to have forward compatible implementations.
type UnimplementedFlightInfoSyncServer struct {
}

func (*UnimplementedFlightInfoSyncServer) GetInfoOnFlight(ctx context.Context, req *GetInfoOnFlightRequest) (*GetFlightReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfoOnFlight not implemented")
}

func RegisterFlightInfoSyncServer(s *grpc.Server, srv FlightInfoSyncServer) {
	s.RegisterService(&_FlightInfoSync_serviceDesc, srv)
}

func _FlightInfoSync_GetInfoOnFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoOnFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlightInfoSyncServer).GetInfoOnFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flightinfoapi.FlightInfoSync/GetInfoOnFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlightInfoSyncServer).GetInfoOnFlight(ctx, req.(*GetInfoOnFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlightInfoSync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flightinfoapi.FlightInfoSync",
	HandlerType: (*FlightInfoSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfoOnFlight",
			Handler:    _FlightInfoSync_GetInfoOnFlight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flightinfo.proto",
}

// FlightInfoAsyncClient is the client API for FlightInfoAsync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlightInfoAsyncClient interface {
	GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (FlightInfoAsync_GetHistoryClient, error)
	KeepSynchronizing(ctx context.Context, opts ...grpc.CallOption) (FlightInfoAsync_KeepSynchronizingClient, error)
}

type flightInfoAsyncClient struct {
	cc *grpc.ClientConn
}

func NewFlightInfoAsyncClient(cc *grpc.ClientConn) FlightInfoAsyncClient {
	return &flightInfoAsyncClient{cc}
}

func (c *flightInfoAsyncClient) GetHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (FlightInfoAsync_GetHistoryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FlightInfoAsync_serviceDesc.Streams[0], "/flightinfoapi.FlightInfoAsync/GetHistory", opts...)
	if err != nil {
		return nil, err
	}
	x := &flightInfoAsyncGetHistoryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FlightInfoAsync_GetHistoryClient interface {
	Recv() (*Flight, error)
	grpc.ClientStream
}

type flightInfoAsyncGetHistoryClient struct {
	grpc.ClientStream
}

func (x *flightInfoAsyncGetHistoryClient) Recv() (*Flight, error) {
	m := new(Flight)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *flightInfoAsyncClient) KeepSynchronizing(ctx context.Context, opts ...grpc.CallOption) (FlightInfoAsync_KeepSynchronizingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FlightInfoAsync_serviceDesc.Streams[1], "/flightinfoapi.FlightInfoAsync/KeepSynchronizing", opts...)
	if err != nil {
		return nil, err
	}
	x := &flightInfoAsyncKeepSynchronizingClient{stream}
	return x, nil
}

type FlightInfoAsync_KeepSynchronizingClient interface {
	Send(*Acknowledgement) error
	Recv() (*FlightPdu, error)
	grpc.ClientStream
}

type flightInfoAsyncKeepSynchronizingClient struct {
	grpc.ClientStream
}

func (x *flightInfoAsyncKeepSynchronizingClient) Send(m *Acknowledgement) error {
	return x.ClientStream.SendMsg(m)
}

func (x *flightInfoAsyncKeepSynchronizingClient) Recv() (*FlightPdu, error) {
	m := new(FlightPdu)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FlightInfoAsyncServer is the server API for FlightInfoAsync service.
type FlightInfoAsyncServer interface {
	GetHistory(*HistoryRequest, FlightInfoAsync_GetHistoryServer) error
	KeepSynchronizing(FlightInfoAsync_KeepSynchronizingServer) error
}

// UnimplementedFlightInfoAsyncServer can be embedded to have forward compatible implementations.
type UnimplementedFlightInfoAsyncServer struct {
}

func (*UnimplementedFlightInfoAsyncServer) GetHistory(req *HistoryRequest, srv FlightInfoAsync_GetHistoryServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (*UnimplementedFlightInfoAsyncServer) KeepSynchronizing(srv FlightInfoAsync_KeepSynchronizingServer) error {
	return status.Errorf(codes.Unimplemented, "method KeepSynchronizing not implemented")
}

func RegisterFlightInfoAsyncServer(s *grpc.Server, srv FlightInfoAsyncServer) {
	s.RegisterService(&_FlightInfoAsync_serviceDesc, srv)
}

func _FlightInfoAsync_GetHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HistoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlightInfoAsyncServer).GetHistory(m, &flightInfoAsyncGetHistoryServer{stream})
}

type FlightInfoAsync_GetHistoryServer interface {
	Send(*Flight) error
	grpc.ServerStream
}

type flightInfoAsyncGetHistoryServer struct {
	grpc.ServerStream
}

func (x *flightInfoAsyncGetHistoryServer) Send(m *Flight) error {
	return x.ServerStream.SendMsg(m)
}

func _FlightInfoAsync_KeepSynchronizing_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FlightInfoAsyncServer).KeepSynchronizing(&flightInfoAsyncKeepSynchronizingServer{stream})
}

type FlightInfoAsync_KeepSynchronizingServer interface {
	Send(*FlightPdu) error
	Recv() (*Acknowledgement, error)
	grpc.ServerStream
}

type flightInfoAsyncKeepSynchronizingServer struct {
	grpc.ServerStream
}

func (x *flightInfoAsyncKeepSynchronizingServer) Send(m *FlightPdu) error {
	return x.ServerStream.SendMsg(m)
}

func (x *flightInfoAsyncKeepSynchronizingServer) Recv() (*Acknowledgement, error) {
	m := new(Acknowledgement)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FlightInfoAsync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flightinfoapi.FlightInfoAsync",
	HandlerType: (*FlightInfoAsyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHistory",
			Handler:       _FlightInfoAsync_GetHistory_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "KeepSynchronizing",
			Handler:       _FlightInfoAsync_KeepSynchronizing_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "flightinfo.proto",
}
