// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/MarcGrol/go-training/examples/swagger/service/models"
)

// CreatePatientOKCode is the HTTP code returned for type CreatePatientOK
const CreatePatientOKCode int = 200

/*CreatePatientOK Returns created patient

swagger:response createPatientOK
*/
type CreatePatientOK struct {

	/*
	  In: Body
	*/
	Payload *models.Patient `json:"body,omitempty"`
}

// NewCreatePatientOK creates CreatePatientOK with default headers values
func NewCreatePatientOK() *CreatePatientOK {

	return &CreatePatientOK{}
}

// WithPayload adds the payload to the create patient o k response
func (o *CreatePatientOK) WithPayload(payload *models.Patient) *CreatePatientOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create patient o k response
func (o *CreatePatientOK) SetPayload(payload *models.Patient) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePatientOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreatePatientDefault Error

swagger:response createPatientDefault
*/
type CreatePatientDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePatientDefault creates CreatePatientDefault with default headers values
func NewCreatePatientDefault(code int) *CreatePatientDefault {
	if code <= 0 {
		code = 500
	}

	return &CreatePatientDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create patient default response
func (o *CreatePatientDefault) WithStatusCode(code int) *CreatePatientDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create patient default response
func (o *CreatePatientDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create patient default response
func (o *CreatePatientDefault) WithPayload(payload *models.Error) *CreatePatientDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create patient default response
func (o *CreatePatientDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePatientDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
