// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPatientsHandlerFunc turns a function with the right signature into a get patients handler
type GetPatientsHandlerFunc func(GetPatientsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPatientsHandlerFunc) Handle(params GetPatientsParams) middleware.Responder {
	return fn(params)
}

// GetPatientsHandler interface for that can handle valid get patients params
type GetPatientsHandler interface {
	Handle(GetPatientsParams) middleware.Responder
}

// NewGetPatients creates a new http.Handler for the get patients operation
func NewGetPatients(ctx *middleware.Context, handler GetPatientsHandler) *GetPatients {
	return &GetPatients{Context: ctx, Handler: handler}
}

/* GetPatients swagger:route GET /patients getPatients

GetPatients get patients API

*/
type GetPatients struct {
	Context *middleware.Context
	Handler GetPatientsHandler
}

func (o *GetPatients) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPatientsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
